Update rails-server.yml

diff --git a/.github/workflows/rails-server.yml b/.github/workflows/rails-server.yml
--- a/.github/workflows/rails-server.yml
+++ b/.github/workflows/rails-server.yml
@@ -18,19 +18,18 @@ jobs:
         with:
           ruby-version: 3.2
           
-      - name: Navigate to server folder
-        run: |
-          cd highscores-api || { echo "Directory 'highscores-api' not found!"; exit 1; }
-          
       - name: Debug current directory
         run: |
           echo "Current directory: $(pwd)"
           echo "Listing files in the current directory:"
           ls -l
           
-      - name: Install Dependencies
+      - name: Navigate to server folder & Install Dependencies
         run: |
-          echo "Checking if Gemfile exists..."
+          cd highscores-api || { echo "Directory 'highscores-api' not found!"; exit 1; }
+          
+          echo "Current directory after cd: $(pwd)"
+          
           if [ -f "Gemfile" ]; then
             echo "Gemfile found"
           else
